apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: root-ca-cert
  namespace: secretgen-test
spec:
  isCA: true
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: client-cert
  namespace: secretgen-test
spec:
  caRef:
    name: root-ca-cert
  extendedKeyUsage:
  - client_auth
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: server-cert
  namespace: secretgen-test
spec:
  caRef:
    name: root-ca-cert
  extendedKeyUsage:
  - client_auth
  - server_auth
  alternativeNames:
  - "eureka-server.service-registry.svc.cluster.local"
  - "eureka-server.service-registry"
  - "eureka-server"
  - "eureka-server-0.eureka-server-headless"
  - "eureka-server-1.eureka-server-headless"
  - "localhost"
