FROM test/nojar

RUN ["rm", "/workspace/BOOT-INF/lib/spring-cloud-bindings-1.11.0.jar"]
COPY spring-cloud-bindings-1.12.0-SNAPSHOT.jar /workspace/BOOT-INF/lib/spring-cloud-bindings-1.12.0-SNAPSHOT.jar

